pipeline:
  name: paprazi_pipe
  identifier: paprazi_pipe
  projectIdentifier: Demo_gitrepo
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: rrahul
        repoName: paprazi_ci
        build: <+input>
  stages:
    - stage:
        name: build
        identifier: build
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  name: Maven Build
                  identifier: MavenBuild
                  type: Run
                  spec:
                    shell: Sh
                    command: |
                      java -version
                      echo "Installing Maven 3.9.6"
                      curl -s https://dlcdn.apache.org/maven/maven-3/3.9.6/binaries/apache-maven-3.9.6-bin.tar.gz -o maven.tar.gz
                      tar -xzf maven.tar.gz
                      mv apache-maven-3.9.6 /opt/maven
                      export PATH=/opt/maven/bin:$PATH
                      mvn -version
                      mvn clean install
                container:
                  image: eclipse-temurin:25-jdk
