pipeline:
  name: paprazi_pipe
  identifier: paprazi_pipe
  projectIdentifier: Demo_gitrepo
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: rrahul
        repoName: paprazi_ci
        build: <+input>
  stages:
    - stage:
        name: build
        identifier: build
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  name: Maven Build
                  identifier: MavenBuild
                  type: Run
                  spec:
                    shell: Sh
                    command: |
                      java -version
                      mvn -version
                      mvn clean install
                container:
                  image: maven:3.9.6-eclipse-temurin-21
