pipeline:
  name: paprazi_pipe
  identifier: paprazi_pipe
  projectIdentifier: Demo_gitrepo
  orgIdentifier: default
  properties:
    ci:
      codebase:
        connectorRef: rrahul
        repoName: paprazi_ci
        build:
          type: branch
          spec:
            branch: main
  stages:
    - stage:
        name: Build_Stage
        identifier: Build_Stage
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Install_JDK_21
                  identifier: Install_JDK_21
                  spec:
                    shell: Bash
                    command: |
                      apt-get update
                      apt-get install -y wget tar
                      wget https://download.java.net/java/GA/jdk21/latest/binaries/openjdk-21_linux-x64_bin.tar.gz
                      tar -xzf openjdk-21_linux-x64_bin.tar.gz -C /opt
                      export JAVA_HOME=/opt/jdk-21
                      export PATH=$JAVA_HOME/bin:$PATH
                      java -version
              - step:
                  type: Run
                  name: Maven_Package
                  identifier: Maven_Package
                  spec:
                    shell: Bash
                    command: |
                      export JAVA_HOME=/opt/jdk-21
                      export PATH=$JAVA_HOME/bin:$PATH
                      mvn -v
                      mvn clean install
              - step:
                  type: RunTests
                  name: Maven_Test_and_Reports
                  identifier: Maven_Test
                  spec:
                    language: Java
                    buildTool: Maven
                    args: test
                    reports:
                      type: JUnit
                      spec:
                        paths:
                          - target/surefire-reports/*.xml
