pipeline:
  name: paprazi_pipe2
  identifier: paprazi_pipe2
  projectIdentifier: Demo_gitrepo
  orgIdentifier: default
  properties:
    ci:
      codebase:
        connectorRef: rrahul
        repoName: paprazi_ci
        build:
          type: branch
          spec:
            branch: main
  stages:
    - stage:
        name: Build_Stage
        identifier: Build_Stage
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Java_and_Maven_Versions
                  identifier: Check_JDK
                  spec:
                    shell: Bash
                    command: |
                      java -version
                      mvn -version
              - step:
                  type: Run
                  name: Maven_Build
                  identifier: Maven_Build
                  spec:
                    shell: Bash
                    command: |
                      mvn clean install
              - step:
                  type: RunTests
                  name: Run_Tests
                  identifier: Run_Tests
                  spec:
                    language: Java
                    buildTool: Maven
                    args: test
                    runOnlySelectedTests: true
                    reports:
                      type: JUnit
                      spec:
                        paths:
                          - target/surefire-reports/*.xml
                    enableTestSplitting: false
              - step:
                  type: Run
                  name: Copy_JAR
                  identifier: Copy_JAR
                  spec:
                    shell: Bash
                    command: |
                      mkdir -p .harness
                      cp target/*.jar .harness/
              - step:
                  type: Run
                  name: Run_4
                  identifier: Run_4
                  spec:
                    shell: Bash
                    command: mvn clean install
