pipeline:
  name: paprazi_pipe
  identifier: paprazi_pipe
  projectIdentifier: Demo_gitrepo
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: rrahul
        repoName: paprazi_ci
        build: <+input>
  stages:
    - stage:
        name: build
        identifier: build
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  name: Install Java 21
                  identifier: InstallJava21
                  type: Run
                  spec:
                    shell: Sh
                    command: |
                      sudo apt-get update
                      sudo apt-get install -y openjdk-21-jdk
                      echo "JAVA VERSION INSTALLED:"
                      java -version
              - step:
                  type: Run
                  name: Maven Build
                  identifier: MavenBuild
                  spec:
                    shell: Sh
                    command: mvn -version && mvn clean install
